# Generated by Django 5.0.4 on 2025-04-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_ftureproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FtureProduct',
            new_name='FutureProduct',
        ),
    ]
