# Generated by Django 5.0.4 on 2025-04-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_ftureproduct_futureproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureproduct',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
